AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python

  Sample SAM Template for python

Globals:
  Function:
    Timeout: 3

Resources:
  createFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: myfunctions/
      Handler: create_blog.create_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete P
        - DynamoDBCrudPolicy:
            TableName: !Ref BlogTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BlogTable
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /create
            Method: POST

  deleteFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: myfunctions/
      Handler: delete_blog.delete_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref BlogTable
      Events:
        blog:
          Type: Api 
          Properties:
            Path: /delete
            Method: DELETE
  
  getFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: myfunctions/
      Handler: get_blogs.get_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete P
        - DynamoDBCrudPolicy:
            TableName: !Ref BlogTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BlogTable
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /get_all
            Method: GET

  filterFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: myfunctions/
      Handler: filter_search.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete P
        - DynamoDBCrudPolicy:
            TableName: !Ref BlogTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BlogTable
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /filter
            Method: GET
  
  updateFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: myfunctions/
      Handler: update_blog.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete P
        - DynamoDBCrudPolicy:
            TableName: !Ref BlogTable
      Environment:
        Variables:
          TABLE_NAME: !Ref BlogTable
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /update
            Method: PUT

  BlogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: BlogTable

Outputs:
  BlogTable:
    Description: "DynamoDB table ARN"
    Value: !GetAtt BlogTable.Arn
