name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and package AWS SAM application
      run: |
        sam build
        sam package --output-template-file packaged.yaml --s3-bucket ${{ secrets.S3_BUCKET_NAME }}

    - name: Deploy AWS SAM application
      uses: aws-actions/aws-sam-deploy@v1
      with:
        stack-name: MyStack
        region: us-west-2
        template-file: packaged.yaml
        capabilities: CAPABILITY_IAM
        s3-bucket: ${{ secrets.S3_BUCKET_NAME }}
        parameter-overrides: |
          MyFunctionName=MyFunction

    - name: Test deployed application
      run: |
        # Run integration tests against the deployed application
